### PR TITLE
Fixed and updated trello integration for issue and suggestions!

### LINKED ISSUE #9: Trello integration fix
Integrating suggestions and issue reports with Trello. Perhaps merging the two lists and adding labels if labels are supported.

### PR DESCRIPTION
**Pull request by Dendrobyte**
Issue reports and suggestions now moved to one channel under the `issue-reports` channel id. Formatting also changed for the card that ends up being added to Trello. Oh yea, **LABEL SUPPORT!**
image

Resolves #9

### CODE REVIEW

File: bot/actions/issueSubmission.js [hunk 1]
```diff
@@ -7,30 +7,57 @@ const trello = new Trello(config.bot.integrations.trello.key, config.bot.integra
 module.exports.checkEvent = async (client, message) => {
     if (message.channel.id === config.bot.channels.issues) {
         let content = message.cleanContent.replace(/\n/g, '');
-        const expression = /Title of issue:\s+(.+)MC or Discord( related)?:\s+(.+)MC username:\s+(.+)World\/channel:\s+(.+)Description:\s(.+)/iu;
+        const expression = /Submission Type:\s+(.+)Title of Submission:\s+(.+)Username:\s+(.+)MC or Discord:\s+(.+)Description:\s(.+)/iu;
```
Comment (Zaph-x) [inline bot/actions/issueSubmission.js:10]: Maybe the "of submission" should be be optional

File: bot/actions/issueSubmission.js [hunk 2]
```diff
@@ -7,30 +7,57 @@ const trello = new Trello(config.bot.integrations.trello.key, config.bot.integra
...
         } else {
-            trello.addCard(match[1], message.cleanContent, config.bot.integrations.trello.lists.issues).then(card => message.attachments.forEach(attachment => {
-                trello.addAttachmentToCard(card.id, attachment.url);
-            }));
+            // Format the message to fit properly on the card
+            const fullMessage = String(message);
+
+            // Get information required for label
+            let labelId = "0000";
+            const cardType = fullMessage.substring(fullMessage.indexOf("Submission Type:") + 16, fullMessage.indexOf("Submission Type:") + 20);
```
Comment (Zaph-x) [inline bot/actions/issueSubmission.js:33]: Any reason we're not using the regex match groups?

File: bot/actions/issueSubmission.js [hunk 3]
```diff
@@ -7,30 +7,57 @@ const trello = new Trello(config.bot.integrations.trello.key, config.bot.integra
...
+            if(cardType.toLowerCase().includes("iss")) {
+                labelId = config.bot.integrations.trello.labels.issue;
+            }
+            else if (cardType.toLowerCase().includes("sug")) {
+                labelId = config.bot.integrations.trello.labels.suggestion;
+            } else {
+                message.member.createDM().then(channel => channel.send(new Discord.RichEmbed()
+                .setAuthor('Please make sure you ONLY "Issue" or "Suggestion" when submitting your report.', null, null)
```
Comment (Zaph-x) [inline bot/actions/issueSubmission.js:41]:
```suggestion
                .setAuthor('Please make sure you ONLY type "Issue" or "Suggestion" as the type, when submitting your report.', null, null)
```

**Review by Zaph-x — COMMENTED** [review]
Looks good. I made some suggestions. Take a look at them and decide whether you like it or not 😄
